
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE EQ ID MINUS NUMBER PLUS PRINT STRING TIMES VARIABLE\n        program : var\n                | print\n        \n        print : PRINT expr\n        \n        var : VARIABLE ID EQ expr \n        \n        mat_op : expr PLUS expr\n               | expr TIMES expr\n               | expr DIVIDE expr\n               | expr MINUS expr\n        \n        expr : NUMBER\n             | ID\n             | mat_op\n             | STRING\n        '
    
_lr_action_items = {'VARIABLE':([0,],[4,]),'PRINT':([0,],[5,]),'$end':([1,2,3,7,8,9,10,11,17,18,19,20,21,],[0,-1,-2,-3,-9,-10,-11,-12,-4,-5,-6,-7,-8,]),'ID':([4,5,12,13,14,15,16,],[6,9,9,9,9,9,9,]),'NUMBER':([5,12,13,14,15,16,],[8,8,8,8,8,8,]),'STRING':([5,12,13,14,15,16,],[11,11,11,11,11,11,]),'EQ':([6,],[12,]),'PLUS':([7,8,9,10,11,17,18,19,20,21,],[13,-9,-10,-11,-12,13,-5,-6,-7,-8,]),'TIMES':([7,8,9,10,11,17,18,19,20,21,],[14,-9,-10,-11,-12,14,14,-6,-7,14,]),'DIVIDE':([7,8,9,10,11,17,18,19,20,21,],[15,-9,-10,-11,-12,15,15,-6,-7,15,]),'MINUS':([7,8,9,10,11,17,18,19,20,21,],[16,-9,-10,-11,-12,16,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'var':([0,],[2,]),'print':([0,],[3,]),'expr':([5,12,13,14,15,16,],[7,17,18,19,20,21,]),'mat_op':([5,12,13,14,15,16,],[10,10,10,10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> var','program',1,'p_program','CLCParser.py',29),
  ('program -> print','program',1,'p_program','CLCParser.py',30),
  ('print -> PRINT expr','print',2,'p_print','CLCParser.py',36),
  ('var -> VARIABLE ID EQ expr','var',4,'p_varAssign','CLCParser.py',42),
  ('mat_op -> expr PLUS expr','mat_op',3,'p_add','CLCParser.py',49),
  ('mat_op -> expr TIMES expr','mat_op',3,'p_add','CLCParser.py',50),
  ('mat_op -> expr DIVIDE expr','mat_op',3,'p_add','CLCParser.py',51),
  ('mat_op -> expr MINUS expr','mat_op',3,'p_add','CLCParser.py',52),
  ('expr -> NUMBER','expr',1,'p_expr','CLCParser.py',67),
  ('expr -> ID','expr',1,'p_expr','CLCParser.py',68),
  ('expr -> mat_op','expr',1,'p_expr','CLCParser.py',69),
  ('expr -> STRING','expr',1,'p_expr','CLCParser.py',70),
]
